<?php

/*
 * You must implement hook_migrate_api(), setting the API level to 2, for
 * your migration classes to be recognized by the Migrate module.
 */
function migrate_politician_revisions_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'PoliticianRevisions' => array(
        'class_name' => 'PoliticianRevisionMigration',
        'group_name' => 'politician_revisions',
      ),
    ),
  );
  return $api;
}

/**
 * Implements hook_update_projects_alter().
 */
function migrate_politician_revisions_update_projects_alter(&$projects) {
  unset($projects['migrate_politician_revisions']);
}
