<?php

/**
 * @file pw_cron_export_submissions.module
 * cron to write submissions to a json file which will be regularly imported by an external civicrm cron
 */


/**
 * Implements hook_cron()..
 */
function pw_cron_export_submissions_cron() {

	// retrieve webform node for newsletter subscriptions
	$internal_path = drupal_lookup_path('source', 'newsletter-subscription');

	if($internal_path && $node = menu_get_object('node', 1, $internal_path)){

		// query db for subscribed & confirmed submissions
		$sql = "SELECT wf_data.sid
				FROM webform_submitted_data wf_data
				LEFT OUTER JOIN webform_confirm_email_code wf_email_code ON wf_data.sid = wf_email_code.sid 
				WHERE wf_data.nid = :nid AND wf_data.data = 'subscribed' AND wf_email_code.code IS NULL";
		$submissions_confirmed = db_query($sql, array(':nid' => $node->nid))->fetchCol();

		if(sizeof($submissions_confirmed) > 0){

			// load webform module
			module_load_include('inc', 'webform', 'includes/webform.submissions');

			// load submissions
			$submissions = webform_get_submissions(array('sid' => $submissions_confirmed));

			// write submissions to json file
			$file_json_content = json_encode($submissions);
			$file_json_path = 'webforms/submissions/newsletter/submissions_'.time().'.json';
			$file_json = file_save_data($file_json_content, 'private://'.$file_json_path, FILE_EXISTS_RENAME);

			// on success update submissions to status=exported
			if($file_json){
				foreach($submissions as $submission){
					$submission->data[2]['value'][0] = 'exported';
					webform_submission_update($node, $submission);
				}
			}
		}
	}
}
